---
name: odoo_db
description: Container de db para odoo
parameters:
-   name: riyic/updates_check_interval
    display_name: Updates check interval
    description: How often check for update with central server (1min,2h,3d)
    field_type: text
    validations:
        regex: "(?-mix:^(never)|\\d+(min|h|d)?)"
    default_value: never
    calculated: 0
    required: 1
    advanced: 0
    data_type: string
    active: 1
    recipe: riyic::default
-   name: riyic/system_locale
    display_name: System locale settings
    description: Default system locale for this system
    field_type: text
    validations:
        regex: "(?i-mx:^(C|POSIX|[a-z]{2,3}\\_[a-z]{2})\\.?[a-z0-9\\-]{0,10}$)"
    default_value: en_US.UTF-8
    calculated: 0
    required: 1
    advanced: 0
    data_type: string
    active: 1
    recipe: riyic::default
-   name: riyic/enable_report
    display_name: Enable chef convergence report
    description: Enable delivery of chef convergence report to riyic
    field_type: radio
    validations:
        fixed_values:
        - 'yes'
        - 'no'
    default_value: 'no'
    calculated: 0
    required: 0
    advanced: 0
    data_type: string
    active: 1
    recipe: riyic::default
-   name: riyic/install_runit_inside_container
    display_name: Installs runit inside container
    description: Installs runit if chef is running inside container?
    field_type: radio
    validations:
        fixed_values:
        - 'yes'
        - 'no'
    default_value: 'yes'
    calculated: 0
    required: 1
    advanced: 0
    data_type: string
    active: 1
    recipe: riyic::default
-   name: riyic/system_timezone
    display_name: System timezone settings
    description: Default system locale for this system
    field_type: text
    validations:
        regex: "(?i-mx:^\\w+\\/\\w+$)"
    default_value: Europe/Madrid
    calculated: 0
    required: 1
    advanced: 0
    data_type: string
    active: 1
    recipe: riyic::default
-   name: dbs/postgresql/server/postgres_password
    display_name: Postgres password
    description: Password for the main postgresql user
    field_type: text
    validations:
        predefined: db_password
    default_value: 
    calculated: 1
    required: 1
    advanced: 0
    data_type: string
    active: 1
    recipe: dbs_postgresql::server
-   name: dbs/postgresql/server/allow_remote_connections
    display_name: Allow remote connections
    description: Configure server to listen in all interfaces instead in localhost
        only
    field_type: radio
    validations:
        fixed_values:
        - 'yes'
        - 'no'
    default_value: 'yes'
    calculated: 0
    required: 0
    advanced: 0
    data_type: string
    active: 1
    recipe: dbs_postgresql::server
-   name: dbs/postgresql/dbs/@/name
    display_name: Database name
    description: Database Name
    field_type: text
    validations:
        predefined: postgresql_identifier
    default_value: odoo
    calculated: 0
    required: 1
    advanced: 0
    data_type: string
    active: 1
    recipe: dbs_postgresql::create_db
-   name: dbs/postgresql/dbs/@/user
    display_name: Database username
    description: Database related user
    field_type: text
    validations:
        predefined: postgresql_identifier
    default_value: odoo
    calculated: 0
    required: 1
    advanced: 0
    data_type: string
    active: 1
    recipe: dbs_postgresql::create_db
-   name: dbs/postgresql/dbs/@/password
    display_name: Database user password
    description: Database user password
    field_type: text
    validations:
        predefined: db_password
    default_value: 
    calculated: 1
    required: 1
    advanced: 0
    data_type: string
    active: 1
    recipe: dbs_postgresql::create_db
recipes:
- riyic::default
- dbs_postgresql::server
- dbs_postgresql::create_db
