---
name: ssl_proxy
description: nginx ssl proxy
parameters:
-   name: riyic/updates_check_interval
    display_name: Updates check interval
    description: How often check for update with central server (1min,2h,3d)
    field_type: text
    validations:
        regex: "(?-mix:^(never)|\\d+(min|h|d)?)"
    default_value: never
    calculated: 0
    required: 1
    advanced: 0
    data_type: string
    active: 1
    recipe: riyic::default
-   name: riyic/system_locale
    display_name: System locale settings
    description: Default system locale for this system
    field_type: text
    validations:
        regex: "(?i-mx:^(C|POSIX|[a-z]{2,3}\\_[a-z]{2})\\.?[a-z0-9\\-]{0,10}$)"
    default_value: en_US.UTF-8
    calculated: 0
    required: 1
    advanced: 0
    data_type: string
    active: 1
    recipe: riyic::default
-   name: riyic/enable_report
    display_name: Enable chef convergence report
    description: Enable delivery of chef convergence report to riyic
    field_type: radio
    validations:
        fixed_values:
        - 'yes'
        - 'no'
    default_value: 'no'
    calculated: 0
    required: 0
    advanced: 0
    data_type: string
    active: 1
    recipe: riyic::default
-   name: riyic/install_runit_inside_container
    display_name: Installs runit inside container
    description: Installs runit if chef is running inside container?
    field_type: radio
    validations:
        fixed_values:
        - 'yes'
        - 'no'
    default_value: 'yes'
    calculated: 0
    required: 1
    advanced: 0
    data_type: string
    active: 1
    recipe: riyic::default
-   name: riyic/system_timezone
    display_name: System timezone settings
    description: Default system locale for this system
    field_type: text
    validations:
        regex: "(?i-mx:^\\w+\\/\\w+$)"
    default_value: Europe/Madrid
    calculated: 0
    required: 1
    advanced: 0
    data_type: string
    active: 1
    recipe: riyic::default
-   name: appserver/nginx/version
    display_name: Nginx version to install
    description: Nginx version to compile and install
    field_type: text
    validations:
        predefined: version
    default_value: 1.6.2
    calculated: 0
    required: 0
    advanced: 0
    data_type: string
    active: 1
    recipe: appserver_nginx::default
-   name: appserver/nginx/checksum
    display_name: Nginx source tarball checksum
    description: Nginx source tarbal sha256 checksum
    field_type: textarea
    validations:
        predefined: checksum
    default_value: b5608c2959d3e7ad09b20fc8f9e5bd4bc87b3bc8ba5936a513c04ed8f1391a18
    calculated: 0
    required: 0
    advanced: 1
    data_type: string
    active: 1
    recipe: appserver_nginx::default
-   name: appserver/nginx/modules
    display_name: Nginx modules
    description: Nginx modules to compile and install with
    field_type: array_input
    validations:
        regex: "(?-mix:^\\w+$)"
    default_value:
    - http_ssl_module
    - http_gzip_static_module
    calculated: 0
    required: 0
    advanced: 1
    data_type: array
    active: 1
    recipe: appserver_nginx::default
-   name: appserver/nginx/install_dir
    display_name: Nginx installation dir
    description: Nginx source installation directory
    field_type: text
    validations:
        predefined: unix_path
    default_value: "/opt/nginx"
    calculated: 0
    required: 0
    advanced: 0
    data_type: string
    active: 1
    recipe: appserver_nginx::default
-   name: appserver/nginx/reverse_proxy_sites/@/domain
    display_name: Site domain
    description: Domain related to site
    field_type: text
    validations:
        predefined: domain
    default_value: default
    calculated: 0
    required: 0
    advanced: 0
    data_type: string
    active: 1
    recipe: appserver_nginx::reverse_proxy
-   name: appserver/nginx/reverse_proxy_sites/@/public_port
    display_name: Public Port
    description: Public port where to bind nginx proxy
    field_type: text
    validations:
        predefined: tcp_port
    default_value: '443'
    calculated: 0
    required: 0
    advanced: 0
    data_type: string
    active: 1
    recipe: appserver_nginx::reverse_proxy
-   name: appserver/nginx/reverse_proxy_sites/@/ssl
    display_name: Use ssl for this site
    description: Has this site an ssl certificate?
    field_type: radio
    validations:
        fixed_values:
        - 'yes'
        - 'no'
    default_value: 'yes'
    calculated: 0
    required: 0
    advanced: 1
    data_type: string
    active: 1
    recipe: appserver_nginx::reverse_proxy
-   name: appserver/nginx/reverse_proxy_sites/@/service_path
    display_name: Service path to map in backend
    description: Path expected for the service in the backend (primarly for websockets)
    field_type: text
    validations:
        predefined: unix_path
    default_value: "/"
    calculated: 0
    required: 0
    advanced: 1
    data_type: string
    active: 1
    recipe: appserver_nginx::reverse_proxy
-   name: appserver/nginx/reverse_proxy_sites/@/backends
    display_name: List of backend servers
    description: List of backend servers in 'ip:port|hostname:port|unix:path' format
    field_type: array_input
    validations:
        predefined: socket_address
    default_value:
    - site0:80
    calculated: 0
    required: 1
    advanced: 0
    data_type: array
    active: 1
    recipe: appserver_nginx::reverse_proxy
-   name: appserver/nginx/reverse_proxy_sites/@/redirect_to_https
    display_name: Redirect http request to https
    description: if this site has ssl, redirect all request from http to https
    field_type: radio
    validations:
        fixed_values:
        - 'yes'
        - 'no'
    default_value: 
    calculated: 0
    required: 0
    advanced: 1
    data_type: string
    active: 1
    recipe: appserver_nginx::reverse_proxy
recipes:
- riyic::default
- appserver_nginx::default
- appserver_nginx::reverse_proxy
